[project]
name = "muos-app"
version = "0.5.0"
description = "A simple muOS app for RomM"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
  "pillow>=12.0",
  "pip>=25.3",
  "pysdl2>=0.9",
  "python-dotenv>=1.2",
  "semver>=3.0",
]
